name: drop_down_search_field
description: Customizable DropdownSearchField extending features DropdownButton, TextFormField and Autocomplete.
version: 1.2.2+1
homepage: https://github.com/rohanjariwala03/drop_down_search_field

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  pointer_interceptor: ^0.10.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
