name: drop_down_search_field
description: Customizable DropdownSearchField extending features DropdownButton, TextFormField and Autocomplete.
version: 0.4.0
homepage: https://github.com/rohanjariwala03/drop_down_search_field

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  pointer_interceptor: ^0.9.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
